veeshan/108048.pl
This updates the Phara Dar script to prevent people from repeatedly re-engaging her and clearing adds to be able to fight her alone.
=> Updates Phara Dar script to prevent exploitative behavior (#58)

lavastorm/#Ruathey.lua, qey2hh1/Ryshon_Hunsti.lua
Ruathey now responds without needing her flag. (Why does she have a flag?)
Ryshon Hunsti now has expected responses highlighted
=> Make Ghoulbane Quest more accurate to wikis

neriakc/Lokar_To-Biath.pl
=> update wine man

plugins/cata_popup_utils.pl
Fixes links pointing to heroesjourneyeq.com
=> Updates links to new site

befallen/player.lua
=> no more Bard only BARD

plugins/soulbinders.pl
people like to say `bind your soul`
=> Allow soulbinders to better accommodate bad grammar

bazaar/151061.pl, bazaar/Apocrypha.pl, bazaar/Tearel.pl, bazaar/Vision_of_Ayonae.pl
=> Fix more bazaar NPCs to return unused items

tox/38139.pl
=> Fixes `undefined` access of `$skelent` in tox

lakeofillomen/#_.pl
=> Fixes incorrect `GetGlobal` access in weird lakeofillomen quest

everfrost/#Kimber_Whitefoot.lua
=> Fix missing nil check for Kimber

lua_modules/desktop.ini, lua_modules/ellipse_box.lua, lua_modules/general_ext.lua, lua_modules/json.lua
Just some general lua_module updates
=> [General] Just some updates to the lua_modules

torgiran/a_Broken_Skull_bloodguard.lua, torgiran/a_Broken_Skull_deathguard.lua, torgiran/a_Broken_Skull_dreadguard.lua, torgiran/a_luggald_abomination.lua, torgiran/a_luggald_arcanist.lua, torgiran/a_luggald_occultist.lua, torgiran/a_luggald_reaver.lua, torgiran/a_water_spirit.lua
Updated with differences between PEQ/WFH and THJ. 
Added missing NPC's to database for Ancient Spirit Ring
=> [Bug Fix] Torg updates

airplane/Dason_Goldblade.lua, airplane/Drakis_Bloodcaster.lua, airplane/Enchanter_Jolas.lua, airplane/Holwin.lua, airplane/Josin_Faithbringer.lua, airplane/Magus_Frinon.lua, airplane/Medicine_Man_Veetra.lua, airplane/Ranger_Spirit.lua, airplane/Sarkis_Ebonblade.lua, airplane/Strandar_Pinemist.lua, airplane/Thalik_Silenthand.lua, airplane/Torgon_Blademaster.lua, airplane/Wizard_Schrock.lua, airplane/player.lua
Prevent questionable conditions with some NPC's
Ensure that Airplane keys are removed on zone out.
=> [Bug Fix] Airplane corrections

frozenshadow/player.lua
- Updated and streamlined logic a bit.
- TOFS Move Characters was not instance aware.
=> [Bug Fix] TOFS Door Scripts

mischiefplane/encounters/Bristlebane_the_King_of_Thieves.lua
- Not Tuning
- Shortened Reset Timer per Feedback
- Added Aggro Linking to prevent more add cheese
=> [Updates] Bristlebane 2.0 Event updates

mischiefplane/encounters/Bristlebane_the_King_of_Thieves.lua
Added seperate add timer to depop incase left up in public zone.
=> [BB] Adds should not depop on BB Death

jaggedpine/#Guard_Finewine.lua, jaggedpine/#Sergeant_Caelin.lua, qcat/Corrupt_Guard_Helminth.lua, qcat/Guard_Helminth.lua, qcat/an_investigator.lua, qeynos/#Donally_Stultz.lua, qeynos/#Riley_Shplots.lua, qeynos/#Willie_Garrote.lua, qeynos/Captain_Tillin.lua, qeynos/an_investigator.lua, qeynos2/#Diseased_Rat.lua, qeynos2/#Enchanted_Rat.lua, qeynos2/#Healthy_Rat.lua, qeynos2/#game_spawner.lua, qeynos2/Vegalys_Keldrane.lua, qeynos2/Velarte_Selire.lua, southkarana/#Theodore_Exanthem.lua, southkarana/an_interrogator.lua
- Rewrote many of the events and flagged them to prevent abuse of some spawns/flags
- This COULD break some users who are mid-way through the events and do not have the appropriate flags.
- Vegalys has the following helpers and notes which step the player should be on for CSR assistance.
---- Quest:Investigators Badge (Badge #1)
-- QGlobal Helpers for Badge Quest #1 (qeynos_badge1) -- 1 = Received Investigator's Briefing
-- 2 = First Suspect
-- 3 = Rileys Confession
-- 4 = Summoned Guard for Riley
-- 5 = Willies Confession
-- 6 = Summoned Guard for Willie
-- 7 = Have the Investigators Badge
-- Failure of the an_investigator section will reset you back to QGlobal 1 so you can restart the escort portion
---- Quest:Interrogator's Badge (Badge #2)
-- QGlobal Helpers for Badge Quest #2 …
=> [Cleanup] Qeynos Badge of Nobility Cleanup

airplane/Drakis_Bloodcaster.lua, paineel/Taralani_Rahnta.lua, paineel/Taralani_Rahnta.pl, skyshrine/#Oglard.lua
- Also fixed some :race to :getracename calls
=> [Bug Fix] Update for Spirit of Garzicor quest

lua_modules/inspect.lua, lua_modules/velious_quest_helper.lua
- Add human readable representations of table functions
=> [Bug] gsub error with race/class names

qeynos2/2177.lua, southkarana/an_interrogator.lua
Fixed per bug report located here: https://discord.com/channels/1204418766318862356/1325367447611506728/1330382562165526670
=> [Bug] Qeynos Badge Fixes

burningwood/Atheling_Plague.lua, cabeast/Hierophant_Dexl.lua, cabeast/Hierophant_Granix.lua, cabeast/Hierophant_Oxyn.lua, cabeast/Hierophant_Zand.lua, cabwest/Jaxxtz.lua, charasis/An_Iksar_Apparition.lua, charasis/Venril_Sathir.lua, charasis/Venril_Sathir.pl, charasis/the_spirit_of_Rile.lua, dalnir/a_coerced_channeler.lua, dalnir/desktop.ini, fieldofbone/Crusader_Quarg.lua, fieldofbone/Oracle_Qulin.lua, fieldofbone/Oracle_Vauris.lua, lakeofillomen/Bruiser_Noz.lua, lakeofillomen/Klok_Sargin.lua, overthere/Galdon_Vok_Nir.lua, swampofnohope/Mystic_Dovan.lua
- Added Flags to each step to monitor progress
- Added faction and level checking per step
- Added notice of flags being assigned (So they are not "Invisible")
- Added Dialog to Oxyn "Progress" that will output current progress point.
Also limited a quest turn in that can be exploited for fast and unlimited XP.
=> [Cleanup] Shaman Cudgel/Skull Quest

jaggedpine/encounters/jpfwar.lua
- Added sanity checks
- Fixed Turn-ins
- DB - Fixed Respawn on non-war village npc's to be 1 hour (2 hours for sarg)
=> [Bug] Fix JPFWar

jaggedpine/encounters/jpfwar.lua
Second commit is more experimental, should work but if it doesn't I will revert that commit.
=> [Bug Fix] Cleanup some JPFWar errors
