- airplane/Sirran_the_Lunatic.lua
Per https://wiki.project1999.com/Plane_of_Sky#Island_7:_Drake_Island, Sister of the Spire should be repeatedly triggerable from Isle 6 by saying this phrase to Sirran. Right now it gets disabled when you first kill her but this doesn't match Live or P99 behavior.
This change makes it so that you can re-trigger Sister still after killing her to match expected behavior.
> Fixes Sirran behavior for Sister of the Spire

- everfrost/Kimber_Whitefoot.lua
should fix
```
[QuestErrors] Zone [everfrost] quests/everfrost/#Kimber_Whitefoot.lua:6: attempt to compare string with nil
stack traceback:
quests/everfrost/#Kimber_Whitefoot.lua:6: in function <quests/everfrost/#Kimber_Whitefoot.lua:4>
```
> Add nil check for kimber_whitefoot script

- innothule/Lynuga.lua
For consideration here -- if it were up to me, I would remove this quest completely -- this reduces the chances of receiving either a Midnight Mallet or Ivandyr's Hoop as a reward from Lynuga.
It's still possible to receive them as rewards but it will be much more expensive to acquire them.
These items can be used to either:
1) Remove the need for including a class with slow in your composition (devalues the utility of slow classes)
2) Trivialize encounters by allowing infinite lifetapping
You can see the bags from a player who posted a screenshot from 3 days into the server here as evidence that it is way too cheap right now to acquire these extremely powerful items:
> Reduce chances of receiving an Ivandyr's Hoop or Midnight Mallet from Lynuga

- airplane/Sirran_the_Lunatic.lua
Per Cata request:
- Allow any key quest item to be turned into Sirran on any island.
- Only allows for one turn-in at a time
- If a player attempts to turn in more than one key quest item, one will be accepted and the rest will be returned
> POSky: Simplifying turn-ins to Sirran

- qey2hh1/Vilnius_the_Small.lua
This PR addresses an issue where certain illusions cause the e.other:Race call to return nil.  The call has been changed to e.other:GetRaceName and has been tested locally.
> Fix getting player race when illusioned

- tox/Assistant_T-os.pl
This should be fixed afterwards to also use a timer like Tolon here:
https://github.com/The-Heroes-Journey-EQEMU/quests/blob/33743b47f43b33b97d14529c142530e906b9dd2a/felwithea/Tolon_Nurbyte.pl#L1-L14
But for now, we don't want this quest to be doable during Classic -- right now this just allows bypassing the entire quest chain.
> Only allow spawning Fleshless Servant if appropriate qglobals are set

- airplane/The_Spiroc_Lord.lua
The script for Spiroc Lord still had the spawn call for Sirran as a unique_spawn.  This resulted in Sirran not spawning on island 5 if he was already up on another island.  Other scripts are just calling the spawn2 method, so this brings things in line with the other spawn calls for Sirran.
> Changing Sirran spawn on Spiroc Lord script to no longer be unique spawn

- timorous/Omat_Vastsea.pl
This adds an option to Omat Vastsea's quest script to summon back Natasha to make it easier for players who ran into issues during the Cleric epic to fix their quest state.
By saying "I wish to see Natasha", they can trigger a spawn of Natasha.
You should also make it so that Natasha is immune to damage / gives no exp or whatever so that people can't exploit this Tolon style (classic).
> Adds quest text to summon Natasha

- airplane/a_presence.lua
- erudnext/Tomekeeper_Danl.lua
- lakerathe/Deep.pl
We've had a few people report that they're not having items returned when working on the Monk epic with the wrong class / at the wrong level.
This _should_ fix it so that they'll get their items back instead of having them eaten.
> Fixes a couple Monk epic chances to check class / level before eating hand in items.

- global/global_player.pl
This fixes a reported exploit where players are intentionally disconnecting their characters from the server with invulnerability effects applied in order to bypass and trivialize raid content.
SPA 40 is invulnerability.
> Fades invulnerability effects when disconnecting from the server

- soltemple/Lon_the_Redeemed.pl
The say link that gets generated in the first part here just says `rogue in need of redemption` and there was a player with a language barrier very confused about why that wasn't working.
This loosens the check to match the say link (it'll also still match the original full text) to avoid confusing Frenchmen interested in questing.
> Loosens quest text check for Burning Rapier

- chardok/Herald_Telcha.pl
Raising this PR as requested by Aporia.  Players were able to get several of the Signets at the same time, once they completed bumping their faction up.  This PR will check the player's inventory (and bank I believe) to ensure they do not have the signet already before issuing the signet.
While I have tested this syntax on my local dev server, I do not have large bags and a rather stock eqemu install.  Based on reviewing other scripts on THJ that do similar things, this should work.
> Prevent players from obtaining more than one starter Di'Zok Signet

- butcher/Gridbar_Galund.lua
- cobaltscar/Yoppa_Greenthumb.lua
- dulak/Quigli.lua
- eastkarana/player.lua
- everfrost/#Kimber_Whitefoot.lua
- everfrost/Kimber_Whitefoot.lua
- firiona/Corfia_Nultethen.lua
- freportn/#Elder_Spirit_of_Enlightenment.lua
- global/items/CHRMFewerMemmed.lua
- hatesfury/Broken_Skull_Armsmaster.lua
- iceclad/Giligatabbus_Igglebix.lua
- jaggedpine/#Derick_Goodroot.lua
- kithicor/Tarnamil.lua
- lakerathe/#Kimm_McShannel.lua
- neriakb/Fleshweaver_T-soma.lua
- oot/Gubblegrot_Smashfist.lua
- poknowledge/Gilina_Yilzior.lua
- poknowledge/Sienn_Kastane.lua
- qey2hh1/Mystik.lua
- sebilis/encounters/desktop.ini
- sebilis/script_init.lua
- swampofnohope/Skurza_Slicekutt.lua
- veksar/player.lua
- warrens/#Wilslik_Gissu.lua
- westwastes/Sir_Elmonious_Falmont.lua
Updated HasClass calls that were incorrect.
Updated most lua scripts with a `epic_disabled` which disabled Epic Pre 1.5/1.5/2.0 scripts. Use a replace all when you get to enabling omens/epics. Also fixed many qglobal checks that did not have nil checks.
> [Bug Fix] HasClass Fixes and soft disabling lua quests with 1.5 mobs

- airplane/Drakis_Bloodcaster.lua
There was still a class check when trying to get the book to spawn Jzil in posky for the cloak turn in.  Removed that class check only on the say phrase of "jzil"
> Removing class check for spawning Jzil (Drakis Bloodcaster)

- hatesfury/encounters/drunken_event.lua
The low drop rate on the reserves (30%) makes this a limiting factor at gathering the items necessary to spawn the Captain in Hate's Fury due to the fact that it enemy that drops it can only be spawned in either the Open world or a non-respawning instance (of which he can only be spawned once per lockout).
This makes a player's ability to kill the Captain inconsistent with how the other bosses are currently handled on the server.  They must either compete for the drops in the open world, which is a static camp.  Or try their luck once a day at the 30% drop rate in non-respawning.
This change switches the controller of the event from the '#drunk_trigger' to 'Attendant Mi`ta'.  This makes the encounter active in all three versions of the instance.  With this behavior players can farm the …
> Switch drunken event controller so it works in all instances.

- eastwastes/#Garadain_Glacierbane.pl
- eastwastes/Garadain_Glacierbane.pl
- eastwastes/Icefang.pl
- eastwastes/Paladin_of_Brell.pl
- eastwastes/Priest_of_Brell.pl
- eastwastes/Royal_Archer.pl
- eastwastes/Royal_Wolven_Guard.pl
The quest script changes are safe to accept, though there are some SQL database changes necessary for things to all work properly.  These changes will be provided directly to THJ server admins for coordinating the updates.
- Quest scripts to support cinematics of the war (move NPCs, speech, etc).
- Updated reward item to be the guaranteed legendary version of the ring.
- Removed many dependencies upon arbitrary timers and more towards event based triggers/signals and waypoints.
- Confirmed Garadain returns any non-expected quest items handed to him during the final turn in.
- Small fix for where Icefang roams to when interacting with Korrigan on ring 6.
Some minor or potential issues that are still in existence:
- There is a race condition that causes some of the military members …
> Add support for Coldain Ring 8 Quest/War

- eastwastes/#Captain_Berradin.pl
- eastwastes/Garadain_Glacierbane.pl
- eastwastes/Korrigain.pl
- greatdivide/118061.lua
- thurgadinb/#Councilor_Juliah_Lockheart.pl
- thurgadinb/#Dain_Frostreaver_IV.pl
- thurgadinb/Councilor_Juliah_Lockheart.pl
- thurgadinb/Seneschal_Aldikar.pl
- Fixed Seneschal social interaction and pathing.  He will not give the box for the 9th ring quest until you show him the 8th ring, follow him to his room, listen to his speech, and say the proper text.  He will walk back up to the throne room after you accept the box from him.  He will not speak to the player while he is moving.
- Fixed Captain Berradin fight so bodyguards properly attack you
- Fixed Korrigan and Garadain quest scripts so that rings are awarded or handed back to you as legendary (item ID + 2 million and used summonfixeditem())
- Fixed the Murdrick quest script to fix an issue where one of his buddies was not attacking due to incorrect ID.  Players do not need to be invisible nor do they need to wait for him to finish his speech.  They can kill him and just ignore the …
> Ring 9 quest script fixes

- hatesfury/encounters/drunken_event.lua
The 'depop' was causing the Attendant to despawn when the player spawned the Buccaneer in a non-respawning instance.  I've removed it since its redundant for two reasons:
1. There's only enough spawns in non-respawning to trigger the spawn once.
2. By not resetting 'killed' back to 0 we will not trigger the correct conditions to spawn it again.
Workaround for now is to simply switch to a respawning instance.
> [Hate's Fury] Fix attendant disappearing on non-respawning.

- cabwest/Harbinger_Glosk.lua
- cabwest/Keeper_Rott.lua
- cabwest/Master_Kyvix.lua
- cabwest/Master_Rixiz.lua
- cabwest/Master_Xydoz.lua
- cabwest/an_Iksar_hermit.lua
- overthere/93182.lua
- overthere/Ixpacan.lua
- overthere/Tin_Banker_Assistant.lua
- Converted each step to its own databucket for tracking. This will prevent step skipping.
- Added missing faction checks
- Added missing flavor text to a few npc's.
NOTE: Players mid way will either need to start over or petition for their progress to be updated as the tracking buckets/globals did not exist prior.
> [Bug Fix] Necromancer Skull Cap

- bazaar/Tearel.pl
- ecommons/Son_of_Tearel.pl
- plugins/cata_general.pl
This unlocks an option on tearel/son of tearel to allow you to not send tells anymore for NPCs.
When this bucket is set, NPCs will use yellowtext similar to instancing when enabled.
> Add option for plugin::NPCTell to not send tells
